### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Liu0329** [DaleSong89/caffe-mt#2]
Hi, I got the following error when I compile the code. Did I miss anything ?
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/data_reader.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/parallel.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/net.cpp
CXX src/caffe/common.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/cudnn_lrn_layer.cpp
CXX src/caffe/layers/eltwise_bn_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/elu_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/scale_layer.cpp
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetBNLayer(const caffe::LayerParameter&)’:
src/caffe/layer_factory.cpp:41:37: error: expected primary-expression before ‘(’ token
     return shared_ptr<Layer<Dtype> >(new ChannlWiseBNLayer<Dtype>(param));
                                     ^
src/caffe/layer_factory.cpp:41:42: error: expected type-specifier before ‘ChannlWiseBNLayer’
     return shared_ptr<Layer<Dtype> >(new ChannlWiseBNLayer<Dtype>(param));
                                          ^
src/caffe/layer_factory.cpp:43:37: error: expected primary-expression before ‘(’ token
     return shared_ptr<Layer<Dtype> >(new EltWiseBNLayer<Dtype>(param));
                                     ^
src/caffe/layer_factory.cpp:43:42: error: expected type-specifier before ‘EltWiseBNLayer’
     return shared_ptr<Layer<Dtype> >(new EltWiseBNLayer<Dtype>(param));
                                          ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetTanHLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:252:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetTanHLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:252:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetSoftmaxLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:229:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetSoftmaxLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:229:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetSigmoidLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:206:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetSigmoidLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:206:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetReLULayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:183:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetReLULayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:183:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetLRNLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:160:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetLRNLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:160:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetPoolingLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:123:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetPoolingLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:123:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetConvolutionLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:86:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetConvolutionLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:86:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetBNLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layer_factory.cpp:47:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/caffe/layer_factory.cpp: In function ‘boost::shared_ptrcaffe::Layer<Dtype > caffe::GetBNLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layer_factory.cpp:47:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: **\* [.build_release/src/caffe/layer_factory.o] Error 1
make: **\* Waiting for unfinished jobs....

**Comment by knsong** [comment]
@Liu0329 It was because the `layer_factory.cpp` missed some header files. I have fixed it. You can try it again.

**Comment by knsong** [comment]
@Liu0329  I've fixed some other compilation errors, now it should be good to use.

**Comment by Liu0329** [comment]
@knsong  OK, thanks !
