### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by liz6688** [DaleSong89/caffe-mt#5]
When I try to Compilation with Make, in "make all" step, I faced the error 
"caffe.proto:385:12: LocalConvolutionParameter" is not defined".
"Makefile:629: recipe for target .build_release/src/caffe/proto/caffe.pb.cc failed"

**Comment by liz6688** [comment]
Add, I also tried your comment in wiki, add related files and parameter to realted caffe files, it also faced a  error: Error parsing text-format caffe.NetParameter: 40:22: Message tyep"caffe.LayerParameter" has no field named "local_conv_param". Did you comfile your caffe_mt file smoothly or faced the same error?

**Comment by knsong** [comment]
I updated it just now and  compiled it with no error. You can pull and compile it again.

**Comment by liz6688** [comment]
I faced a new error: 
Makefile:616: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1
In addition, I tried your comment in wiki, why I can't build a model?

**Comment by knsong** [comment]
Please update more details about the error.

**Comment by liz6688** [comment]
Case1: when compile the caffe-mt, the error is:
.build_release/lib/libcaffe.so：对‘google::protobuf::DescriptorPool::FindFileByName(std::string const&) const’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::Message::InitializationErrorString() const’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:616: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1

Case2: I tried your comment in wiki, I face the error:
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 40:22: Message type "caffe.LayerParameter" has no field named "local_conv_param".
F0308 16:28:42.470536 14421 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: prototxt/1_F_train.prototxt

**Comment by knsong** [comment]
@liz6688  I used `protobuff` of version 2.5.0 and you should make sure that you linked the right protobuff libraries.

**Comment by liz6688** [comment]
My version is 2.6.1 doesn't it right？

**Comment by knsong** [comment]
It doesn't matter, but you  should make sure that you linked the right protobuff libraries because you got link errors.
